# localstorage : mongo-pvc

#pvc describes- what do we want.
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pvc
spec:
  storageClassName: mylocalstorage
  accessModes:
    - ReadWriteOnce #check in the document for other modes.
  resources:
    request:
      storage: 20Gi
  

---
#persistent volume - how do we want.
apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-storage
spec:
  storageClassName: mylocalstorage
  capacity:
    storage: 20Gi  #total capacity
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/some/dir/structure/"
    type: DirectoryOrCreate